### ISSUE TITLE
storeCallback of CustomSessionStorage has id as "offline_" -> shop id missing

### ISSUE THREAD

**Issue by luciilucii** [Shopify/koa-shopify-auth#111]
# Issue summary
When trying to redirect the merchant to a charge url, the session in the store callback doesn't have a shop value, and the id is "offline_". The shop is actually an empty string in that case.

## Expected behavior
The merchant should be redirected to the charge url.

## Actual behavior
The merchant is redirected to an URL that doesn't contain any grant_options. Therefore the page doesn't work and the browser shows the following error:

"This site can’t be reached. Check if there is a typo in admin."

## Steps to reproduce the problem
Haven't found out how to clearly reproduce the problem. Reinstalling the app doesn't solve the issue. Neither does changing the ngrok link nor reauthenticating via the partner dashboard for the development store.

When trying the last time, I logged in to a different shop after installing the app in the first shop. After a while, I returned to the first shop. But not entirely sure that this causes the problem.

## Important Note
I use both offline and online authentication like described here:
https://github.com/Shopify/koa-shopify-auth/issues/106

---

**Comment by luciilucii** [comment]
Hey @paulomarg 

I got the error again. Unfortunately also not sure why this was caused.

However, I got the trace nailed down: 

    at CustomSessionStorage.storeCallback (/Users/.../server/sessionHandler.js:44:27)
    at CustomSessionStorage.<anonymous> (/Users/.../node_modules/@shopify/shopify- 
    api/dist/auth/session/storage/custom.js:23:51)
    at step (/Users/.../node_modules/@shopify/shopify-api/node_modules/tslib/tslib.js:143:27)
    at Object.next (/Users/.../node_modules/@shopify/shopify-api/node_modules/tslib/tslib.js:124:57)
    at /Users/.../node_modules/@shopify/shopify-api/node_modules/tslib/tslib.js:117:75
    at new Promise (<anonymous>)
    at Object.__awaiter (/Users/.../node_modules/@shopify/shopify-api/node_modules/tslib/tslib.js:113:16)
    at CustomSessionStorage.storeSession (/Users/.../node_modules/@shopify/shopify-    api/dist/auth/session/storage/custom.js:17:24)
    at Object.<anonymous> (/Users/.../node_modules/@shopify/shopify-api/dist/auth/oauth/oauth.js:49:80)
    at step (/Users/.../node_modules/@shopify/shopify-api/node_modules/tslib/tslib.js:143:27)
    at CustomSessionStorage.storeCallback (/Users/.../server/sessionHandler.js:47:25)
    at CustomSessionStorage.<anonymous> (/Users/.../node_modules/@shopify/shopify-api/dist/auth/session/storage/custom.js:23:51)
    at step (/Users/.../node_modules/@shopify/shopify-api/node_modules/tslib/tslib.js:143:27)
    at Object.next (/Users/.../node_modules/@shopify/shopify-api/node_modules/tslib/tslib.js:124:57)
    at /Users/.../node_modules/@shopify/shopify-api/node_modules/tslib/tslib.js:117:75
    at new Promise (<anonymous>)
    at Object.__awaiter (/Users/.../node_modules/@shopify/shopify-api/node_modules/tslib/tslib.js:113:16)
    at CustomSessionStorage.storeSession (/Users/.../node_modules/@shopify/shopify-api/dist/auth/session/storage/custom.js:17:24)
    at Object.<anonymous> (/Users/.../node_modules/@shopify/shopify-api/dist/auth/oauth/oauth.js:49:80)
    at step (/Users/.../node_modules/@shopify/shopify-api/node_modules/tslib/tslib.js:143:27)`
