### ISSUE TITLE
Why isn't createShopifyAuth documented in README.md?

### ISSUE THREAD

**Issue by RavenHursT** [Shopify/koa-shopify-auth#154]
# Issue summary

Write a short description of the issue here ↓

This is more of a "question" than a "bug", but it seems GH Discussions aren't enabled on this repo, and the issue creation flow have an option to ask a question, so I'm doing it this way. I hope that's ok 😬 

I see instructions for how to use `shopifyAuth` middleware.  But most of the examples I've seen across the interwebs, plus the app that I've inherited, that I'm currently working on, are using `createShopifyAuth`: https://github.com/Shopify/koa-shopify-auth/blob/master/src/auth/index.ts#L33

I keep having to jump to that source code just to know how it behaves, what args I should send it, etc.

## Expected behavior

What do you think should happen?

Would be nice to have this area properly documented, w/ some kind of explanation of the diff between `shopifyAuth` and `createShopifyAuth`

## Actual behavior

What actually happens?

Have to read and interpret source code to use `createShopifyAuth`

**Comment by technologytesting** [comment]
Would be helpful as well since our app was built with createShopifyAuth too, and since updating to 5.0.3 have been facing issues

**Comment by Draccano** [comment]
I am facing a similar problem. The version 5.* use -**shopifyAuth** instead of **createShopifyAuth** [source](https://github.com/Shopify/koa-shopify-auth#shopifyauth). I just upgraded the version, but if I change the imported method to shopifyAuth, there occurs an error shown below 
```
  InternalServerError: response is not defined
      at Object.throw (C:\Bohemi Interactive\shopify\client\node_modules\koa\lib\context.js:97:11)
      at C:\Bohemi Interactive\shopify\client\node_modules\@shopify\koa-shopify-auth\dist\src\auth\index.js:107:42
      at step (C:\Bohemi Interactive\shopify\client\node_modules\@shopify\koa-shopify-auth\node_modules\tslib\tslib.js:141:27)
      at Object.throw (C:\Bohemi Interactive\shopify\client\node_modules\@shopify\koa-shopify-auth\node_modules\tslib\tslib.js:122:57)
      at rejected (C:\Bohemi Interactive\shopify\client\node_modules\@shopify\koa-shopify-auth\node_modules\tslib\tslib.js:113:69)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)

server error InternalServerError: response is not defined
    at Object.throw (C:\Bohemi Interactive\shopify\client\node_modules\koa\lib\context.js:97:11)
    at C:\Bohemi Interactive\shopify\client\node_modules\@shopify\koa-shopify-auth\dist\src\auth\index.js:107:42
    at step (C:\Bohemi Interactive\shopify\client\node_modules\@shopify\koa-shopify-auth\node_modules\tslib\tslib.js:141:27)
    at Object.throw (C:\Bohemi Interactive\shopify\client\node_modules\@shopify\koa-shopify-auth\node_modules\tslib\tslib.js:122:57)
    at rejected (C:\Bohemi Interactive\shopify\client\node_modules\@shopify\koa-shopify-auth\node_modules\tslib\tslib.js:113:69)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

The strange thing here is that if I use the deprecated **createShopifyApp**, the app works well.
